-- Prospecting cloud MVP: Supabase/Postgres version of the local SQLite schema.
-- Public browser clients do not touch these tables directly. Next.js server routes
-- use SUPABASE_SECRET_KEY, so grants stay limited to service_role for the demo.

create table if not exists public.companies (
  duns text primary key,
  nip text,
  company_name text not null,
  tradestyle text,
  domain text,
  city text,
  region text,
  postal_code text,
  country text,
  industry text,
  pkd text,
  sales_eur numeric,
  employees_total integer,
  employees_reliable integer default 1,
  is_headquarters integer,
  business_desc text,
  branch_group text,
  branch_flag integer default 0,
  branch_resolved integer default 0,
  blocked integer default 0,
  blocked_reason text,
  direct_marketing_optout integer,
  source text default 'dnb',
  imported_at timestamptz default now(),
  updated_by text default 'import' check (updated_by in ('ai', 'operator', 'import', 'system')),
  updated_at timestamptz default now()
);

create table if not exists public.campaigns (
  id bigint generated by default as identity primary key,
  name text not null,
  date_from date,
  date_to date,
  goal text,
  status text not null default 'zaproponowana'
    check (status in ('zaproponowana', 'planowana', 'aktywna', 'zamknieta')),
  created_at timestamptz default now(),
  updated_by text default 'operator' check (updated_by in ('ai', 'operator', 'import', 'system'))
);

create table if not exists public.people (
  id bigint generated by default as identity primary key,
  duns text not null references public.companies(duns),
  first_name text,
  last_name text,
  title text,
  contact_level text,
  job_function text,
  email text,
  email_type text check (email_type in ('personal', 'generic', 'none')),
  contactability text check (contactability in ('A', 'B', 'C', 'D')),
  phone text,
  source text check (source in ('dnb', 'apollo')),
  is_dnb_anchor integer default 0,
  icp_profile text,
  apollo_status text check (apollo_status in ('pending', 'matched', 'not_found', 'skipped')),
  ready_for_outreach integer default 0,
  ready_reason text,
  assessed_at timestamptz,
  selected_for_outreach integer default 0,
  campaign_id bigint references public.campaigns(id),
  optout integer default 0,
  status text not null default 'sourced' check (status in (
    'sourced', 'enriched', 'awaiting_selection', 'selected',
    'sent', 'replied', 'qualified', 'booked',
    'won', 'lost', 'nurture', 'rejected', 'suppressed'
  )),
  last_touch_at timestamptz,
  followups_sent integer default 0 check (followups_sent <= 2),
  created_at timestamptz default now(),
  updated_by text default 'import' check (updated_by in ('ai', 'operator', 'import', 'system')),
  updated_at timestamptz default now(),
  unique (duns, last_name, first_name, title)
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('company', 'person')),
  entity_id text not null,
  event_type text not null,
  actor text check (actor in ('ai', 'operator', 'system')),
  payload jsonb,
  at timestamptz default now()
);

create table if not exists public.suppression (
  email text primary key,
  reason text,
  added_by text,
  added_at timestamptz default now()
);

create table if not exists public.raw_import (
  id bigint generated by default as identity primary key,
  import_id text not null,
  row_json jsonb not null,
  imported_at timestamptz default now()
);

create table if not exists public.import_log (
  id bigint generated by default as identity primary key,
  import_id text not null,
  file_name text,
  rows_in_file integer,
  companies_new integer,
  companies_dup integer,
  people_new integer,
  people_dup integer,
  state_a integer,
  state_b integer,
  state_c integer,
  state_d integer,
  branch_flags integer,
  notes text,
  created_at timestamptz default now()
);

create index if not exists idx_comp_industry on public.companies(industry);
create index if not exists idx_comp_region on public.companies(region);
create index if not exists idx_comp_branch on public.companies(branch_flag) where branch_flag = 1;
create index if not exists idx_people_duns on public.people(duns);
create index if not exists idx_people_status on public.people(status);
create index if not exists idx_people_selected on public.people(selected_for_outreach) where selected_for_outreach = 1;
create index if not exists idx_people_email on public.people(email);
create index if not exists idx_people_contact on public.people(contactability);
create index if not exists idx_people_campaign on public.people(campaign_id);
create index if not exists idx_people_ready on public.people(ready_for_outreach) where ready_for_outreach = 1;
create index if not exists idx_events_entity on public.events(entity_type, entity_id, at);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists people_touch on public.people;
create trigger people_touch
before update on public.people
for each row execute function public.touch_updated_at();

drop trigger if exists comp_touch on public.companies;
create trigger comp_touch
before update on public.companies
for each row execute function public.touch_updated_at();

create or replace view public.company_status
with (security_invoker = true)
as
with agg as (
  select
    duns,
    count(*) as n_people,
    sum(case when status in ('sent', 'replied', 'qualified', 'booked', 'won', 'lost', 'nurture') then 1 else 0 end) as n_contacted,
    sum(case when status in ('sourced', 'enriched', 'awaiting_selection', 'selected') and optout = 0 then 1 else 0 end) as n_available,
    sum(case when status in ('sourced', 'enriched', 'awaiting_selection', 'selected') and optout = 0 and ready_for_outreach = 1 then 1 else 0 end) as n_ready,
    sum(case when status in ('replied', 'qualified', 'booked', 'won') then 1 else 0 end) as n_positive,
    sum(case when status = 'won' then 1 else 0 end) as n_won,
    sum(case when selected_for_outreach = 1 then 1 else 0 end) as n_selected
  from public.people
  group by duns
)
select
  c.*,
  coalesce(a.n_people, 0) as n_people,
  coalesce(a.n_contacted, 0) as n_contacted,
  coalesce(a.n_available, 0) as n_available,
  coalesce(a.n_ready, 0) as n_ready,
  coalesce(a.n_positive, 0) as n_positive,
  coalesce(a.n_selected, 0) as n_selected,
  case
    when c.blocked = 1 then 'zablokowana'
    when coalesce(a.n_won, 0) > 0 then 'klient'
    when coalesce(a.n_positive, 0) > 0 then 'w_grze'
    when coalesce(a.n_contacted, 0) = 0 then 'nowa'
    when coalesce(a.n_available, 0) > 0 then 'napoczeta'
    else 'wyczerpana'
  end as company_status
from public.companies c
left join agg a on a.duns = c.duns;

alter table public.companies enable row level security;
alter table public.campaigns enable row level security;
alter table public.people enable row level security;
alter table public.events enable row level security;
alter table public.suppression enable row level security;
alter table public.raw_import enable row level security;
alter table public.import_log enable row level security;

revoke all on table public.companies from anon, authenticated;
revoke all on table public.campaigns from anon, authenticated;
revoke all on table public.people from anon, authenticated;
revoke all on table public.events from anon, authenticated;
revoke all on table public.suppression from anon, authenticated;
revoke all on table public.raw_import from anon, authenticated;
revoke all on table public.import_log from anon, authenticated;
revoke all on table public.company_status from anon, authenticated;

grant select, insert, update, delete on table public.companies to service_role;
grant select, insert, update, delete on table public.campaigns to service_role;
grant select, insert, update, delete on table public.people to service_role;
grant select, insert, update, delete on table public.events to service_role;
grant select, insert, update, delete on table public.suppression to service_role;
grant select, insert, update, delete on table public.raw_import to service_role;
grant select, insert, update, delete on table public.import_log to service_role;
grant select on table public.company_status to service_role;
grant usage, select on all sequences in schema public to service_role;
